//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaMAD.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NominaMAD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;!-- Mes y Año en la esquina superior derecha --&gt;
        ///    &lt;table style=&quot;width:100%; margin-bottom: 10px;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: right;&quot;&gt;&lt;strong&gt;Mes:&lt;/strong&gt; @MES_NOMINA &lt;strong&gt;Año:&lt;/strong&gt; @ANO_NOMINA&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/table&gt;
        ///
        ///    &lt;!-- Datos de la Empresa --&gt;
        ///    &lt;table border=&quot;1&quot; style=&quot;width:100%; margin-bottom: 20px;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; align=&quot;center&quot;&gt;&lt;h2&gt;Recibo de Nómina&lt;/h2&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla {
            get {
                return ResourceManager.GetString("plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .header {
        ///            text-align: right;
        ///            font-weight: bold;
        ///            margin-bottom: 10px;
        ///        }
        ///
        ///        .title {
        ///            text-align: center;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .table {
        ///            width: 100%;
        ///            border-collapse: collapse;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///            .table th, .table td  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Reporte_Departamentos {
            get {
                return ResourceManager.GetString("Reporte_Departamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .header {
        ///            text-align: right;
        ///            font-weight: bold;
        ///            margin-bottom: 10px;
        ///        }
        ///
        ///        .title {
        ///            text-align: center;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .table {
        ///            width: 100%;
        ///            border-collapse: collapse;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .table th, .table td {
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Reporte_Puestos {
            get {
                return ResourceManager.GetString("Reporte_Puestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .header {
        ///            text-align: right;
        ///            font-weight: bold;
        ///            margin-bottom: 10px;
        ///        }
        ///
        ///        .title {
        ///            text-align: center;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .table {
        ///            width: 100%;
        ///            border-collapse: collapse;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .table th, .table td {
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Reporte_Turnos {
            get {
                return ResourceManager.GetString("Reporte_Turnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .header {
        ///            text-align: right;
        ///            font-weight: bold;
        ///            margin-bottom: 10px;
        ///        }
        ///
        ///        .title {
        ///            text-align: center;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .employee-section {
        ///            margin-bottom: 30px;
        ///            border: 1px solid #000;
        ///            padding: 15px;
        ///        }
        ///
        ///        .employee-info  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ReporteGeneral_Kardex_ {
            get {
                return ResourceManager.GetString("ReporteGeneral_Kardex_", resourceCulture);
            }
        }
    }
}
